import Head from 'next/head'
import Image from 'next/image';
import styles from '../styles/Home.module.css'
import Typewriter from '../components/ui/typewriter'
import { useEffect, useState } from 'react';



export default function Home() {
  const [typtext,settyptext]=useState('');
  var i = 0;
  var txt = 'Learn to recognize good luck when it’s waving at you, hoping to get your attention.';
  var speed = 100;
  var newtext='';

  useEffect(()=>{
    typeWriter();
  },[])

  function typeWriter() {
   
    if (i < txt.length) {
      // document.getElementById("demo").innerHTML += txt.charAt(i);
      newtext+=txt.charAt(i);
      settyptext(newtext);
      i++;
      setTimeout(typeWriter, speed);
    }
  }

  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
      <link href="https://fonts.googleapis.com/css2?family=Big+Shoulders+Stencil+Text:wght@600;900&family=Montserrat:ital,wght@0,100;0,200;0,300;0,400;0,500;1,100;1,200&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Press+Start+2P&display=swap" rel="stylesheet"/>
      </Head>

      
     


    <div className="bg-[url('/img/fpage.png')]  bg-cover bg-no-repeat bg-center h-screen w-screen ">
    <div className='2xl:ml-72 md:ml-28 2xl:w-full  xl:w-4/5 xl:h-1/5 '>
      <Image src="/img/lottery.png" alt="No Image" width={400} height={110} />
    </div>
    <div className='2xl:ml-96 -mt-10 2xl:w-full  xl:w-4/5 xl:h-1/5 md:ml-36 '>
      <Image src="/img/luckyfour.png" alt="No Image" width={300} height={200} />
     
    </div>
    <div className='pt-2 xl:mt-5 2xl:pt-10 md:pt-20 text-white'>
    <div className='text-white'>
    <p id="demo" className='md:text-4xl ml-5 xl:ml-28 lg:ml-20 text-lime-400 md:font-stencil font-black sm:font-poppins text-lg'>{typtext}</p>
    </div>
    </div>

    {/* <div >
    <div className='absolute 2xl:ml-96 xl:ml-56 mt-5 2xl:w-full 2xl:h-full xl:w-2/5  '>
    <Image src="/img/changeone.png" alt="No Image" width={800} height={300} />
    </div>
    </div> */}
   
   
    
   
    </div>


    

    </div>
  )
}
